[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/pages/devis"
  to = "/pages/devis.html"
  status = 200

[[redirects]]
  from = "/pages/transport"
  to = "/pages/transport.html"
  status = 200

[[redirects]]
  from = "/pages/automobile"
  to = "/pages/automobile.html"
  status = 200

[[redirects]]
  from = "/pages/pieces"
  to = "/pages/pieces.html"
  status = 200

[[redirects]]
  from = "/pages/import-export"
  to = "/pages/import-export.html"
  status = 200

[[redirects]]
  from = "/pages/contact"
  to = "/pages/contact.html"
  status = 200

[[redirects]]
  from = "/pages/merci"
  to = "/pages/merci.html"
  status = 200
